version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" 
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000  
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

